name: Build D on Pull Request

on:
  pull_request:
    paths:
      - 'package-d/**'

jobs:
  call-workflow:
    uses: JoshNavi/monorepo-reusable-workflow-example/.github/workflows/build.yml@main
    with:
      name: 'package-d'
